.TH LINUX-CHECK-REMOVAL 1 "6 June 2016"
.SH NAME
linux\-check\-removal \- check whether removal of a kernel is safe
.SH SYNOPSIS
.HP
.BI linux\-check\-removal \ KERNEL\-VER
.SH DESCRIPTION
\fBlinux\-check\-removal\fR is intended to be called from the prerm
maintainer scripts of Linux kernel packages.
.PP
The \fIKERNEL\-VER\fR argument must be the kernel version string as shown by
\fBuname \-r\fR and used in filenames, not the package version.
.PP
If the currently running kernel matches \fIKERNEL\-VER\fR,
\fBlinux\-check\-removal\fR normally prompts the user to confirm
this potentially dangerous action and fails if the user chooses to
abort.  There are two exceptions to this behaviour:
.IP \(bu 2
If the current environment is a chroot or container, it is assumed
that the running kernel is independent of any installed kernel package
and the command always quietly succeeds
.IP \(bu 2
If debconf prompts are disabled, the command warns if removing the
running kernel but always succeeds

.SH ENVIRONMENT VARIABLES
.PD 0
.TP
.I DEBIAN_FRONTEND
Name of the preferred debconf front-end.  If set to
\fInoninteractive\fR, debconf prompts are disabled and
\fBlinux\-check\-removal\fR always quietly succeeds.
.TP
.I DPKG_MAINTSCRIPT_PACKAGE
Name of the package to be removed, automatically set by dpkg.

.SH AUTHOR
\fBlinux\-check\-removal\fR and this manual page were written by Ben
Hutchings as part of the Debian \fBlinux\-base\fR package.
